services:
  - type: web
    name: subjectify-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend  # ðŸ‘ˆ Add this line
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
